services:
  kuda_fastapi_app:
    env_file:
      - .env
    build:
      context: backend/app
    container_name: kuda_fastapi_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=kuda_database
      - REDIS_HOST=kuda_redis
    depends_on:
      - kuda_database
      - kuda_redis
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000


  kuda_database:
    env_file:
      - .env
    image: postgres:latest
    restart: always
    container_name: kuda_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - kuda_database:/var/lib/postgresql/data

  kuda_redis:
    image: redis:6
    container_name: kuda_redis
    ports:
      - "6379:6379"

volumes:
  kuda_database:
