services:

  kuda_test_database:
    env_file:
      - ./backend/.env
    image: postgres:latest
    restart: always
    container_name: kuda_test_database
    environment:
      POSTGRES_USER: ${APP_CONFIG__TEST_DATABASE__DB_USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__TEST_DATABASE__DB_PASSWORD}
      POSTGRES_DB: ${APP_CONFIG__TEST_DATABASE__DB_NAME}
    ports:
      - "5434:5432"


  kuda_redis:
    image: redis:6
    container_name: kuda_redis
    ports:
      - "6379:6379"

