services:

  kuda_test_database:
    env_file:
      - .env
    image: postgres:latest
    restart: always
    container_name: kuda_test_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    ports:
      - "5434:5432"


  kuda_redis:
    image: redis:6
    container_name: kuda_redis
    ports:
      - "6379:6379"

