services:
  fastapi_app:
    env_file:
      - .env
    build:
      context: ./app
    container_name: fastapi_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=database
      - REDIS_HOST=redis
    depends_on:
      - database
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000


  database:
    env_file:
      - .env
    image: postgres:latest
    restart: always
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  database:
