name: Deploy Docker Compose Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create SSH key file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key

      - name: Check SSH connectivity
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo SSH connection established"
          
      - name: Update repository on remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /kuda && git pull'

      - name: Create .env file from secrets
        run: |
          touch .env
          for secret in $(printenv | grep -vE '^(GITHUB|RUNNER|SSH_)' | cut -d'=' -f1); do
            key=$secret
            value=${!secret}
            echo "$key=$value" >> .env
          done
          chmod 600 .env
          cat .env

      - name: Copy .env file to remote server
        run: |
          scp -o StrictHostKeyChecking=no -i ssh_key .env ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/kuda/
      
      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /kuda
            docker compose up --build -d
          EOF
      - name: Cleanup local .env file
        run: rm -f .env
        
      - name: Cleanup SSH key file
        run: rm -f ssh_key
